index_location:
    path:     /location
    defaults: { _controller: PlanningBundle:Location:index }

site_list:
    path:     /location/sites
    defaults: { _controller: PlanningBundle:Location:siteList }

room_list:
    path:     /location/rooms
    defaults: { _controller: PlanningBundle:Location:roomList }

site:
    path:     /location/site-{id}
    defaults: { _controller: PlanningBundle:Location:site }

room:
    path:     /location/room-{id}
    defaults: { _controller: PlanningBundle:Location:room }

add_site:
    path:     /location/site/new
    defaults: { _controller: PlanningBundle:Location:addSite }

add_room:
    path:     /location/room/new
    defaults: { _controller: PlanningBundle:Location:addRoom }

edit_site:
    path:     /location/site-{id}/edit
    defaults: { _controller: PlanningBundle:Location:editSite }

edit_room:
    path:     /location/room-{id}/edit
    defaults: { _controller: PlanningBundle:Location:editRoom }

delete_room:
    path:     /location/room-{id}/delete
    defaults: { _controller: PlanningBundle:Location:deleteRoom }